### ISSUE TITLE
Do we really need to create a token?

### ISSUE THREAD

**Issue by dmidlo** [mateogianolio/openblog#17]
the no-scope personal access token still grants read-only access to private repos.  I tested using just `"x"` as my token and it works just fine since github's api is read-only by default for public repos.  Maybe test out some different scenarios to see if this is true.  if it is, remove the token requirement from your documentation and hard-code the token to "x" as I have done.

here's my sample using `"x"` as the token:
https://dmidlo.github.io/blog/

- open it up in devtools, look at elements > head > script
- My token is assigned to the const TOKEN

**Comment by mateogianolio** [comment]
Hi :) If I remember correctly the token is to avoid/decrease api throttling by Github, but if your site is low-traffic it is probably not necessary. Maybe a note about this in the README and changing the token to `x` by default. Thanks for creating an issue!

**Comment by dmidlo** [comment]
I wonder if that even matters in regard to throttling.  This code is delivered to each individual client/requester and not run from a centralized place.  I think that means each client's "app" is used against their own quota.  

I think the traditional use of the api would be to have some code on a server somewhere, and for each person that visited your blog, they would place a request against your server, and then your server would then place a request against the api.  Thus the single source for all blog traffic is represented by just your server and its IP address and the token that is securely tucked away on it.

But here this is not the case, because there is no single server, but instead, the run-time code is delivered to each client and thus distributing the requests across all viewers of the blog...

I spent a bit trying to find confirmation on how throttling is counted in this regard, but I'm not finding anything other than the limit numbers...  I think each individual reader of your blog is using their own quota in this scenario, that is unless you DO provide a token which then everyone counts against the one token.

Let me know if you can find any more info on it

**Comment by mateogianolio** [comment]
Found the relevant part of the docs!

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour.
> Unauthenticated requests are associated with the originating IP address, and not the person making requests.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

So, 60 requests per hour (which in itself is low) coupled with the fact that the requests "are associated with the originating IP address, and not the person making requests" makes the need for a token obvious.

**Comment by dmidlo** [comment]
No.  Do not include a token.    I really do believe this to be a terrible idea and it's irresponsible to suggest that it is required, and if not that... just totally unnecessary.

The personal access token is absolutely meant for use inside of a walled garden.  Even the 'read-only' work-around still provides read-only access to all private repositories owned by an account.  It's a terrible idea.

Additionally, your interpretation of the docs here is just completely incorrect.  I mostly covered this in my last reply, but with the docs in front of us we can sort this out.

You highlighted the idea from the docs of an 'originating ip address';

Here's the idea:

let's say my home ip address is x.x.x.x and your home ip address is y.y.y.y.  

In my home I have a computer with a web browser, and in your home you also have a computer with a web browser.  

When I go to https://casualjavascript.com/ it places a request to github pages (which has no rate-limiting at all) to download the blog assets, which, for your build here is elegant and simple... a simple html document.

that simple html document is parsed by my browser in my home from the ip address of x.x.x.x.  

The browser then downloads scripts from some CDNs and then places a request to the github api (which is the rate-limited service).  

So when I do that, the github rate-limiter ticks the box on my limit marking x.x.x.x as the 'originating ip address'.  

1 of 60 for the hour for x.x.x.x

then I refresh the page to see if there are new posts on https://casualjavascript.com/ and there isn't anything new yet, so I refresh the page again... and again

2 of 60 for the hour for x.x.x.x
3 of 60 for the hour for x.x.x.x
4 of 60 for the hour for x.x.x.x
5 of 60 for the hour for x.x.x.x
...
59 of 60 for the hour for x.x.x.x
60 of 60 for the hour for x.x.x.x

then the rate limiter kicks in and says, nope! no more! go touch some grass... 

but here's the point I was trying to make earlier, you in your home with an ip address of y.y.y.y can sit and load up the page just fine, because your originating IP address is different than mine, you'd start all on your own with:

1 of 60 for the hour for y.y.y.y

So even for your high-traffic blog, because each new visitor likey has a unique originating IP address, and thus their own rate-limit.

Again, the token is meant for use behind a walled garden, and the rate-limit is a big deal if the API requests were placed from a traditional app server.   let's say the app server has an ip address of z.z.z.z

so, you and I both want to visit your blog, so I type in the URL, you type in the URL and DNS tells us that your domain name is located at your app server's address....   z.z.z.z

x.x.x.x (me) -----> z.z.z.z -----> github api          
y.y.y.y (you) --------^

every time I or you want to refresh the page, we first must ask your app server to send a request.... for each user of the blog.

so no matter who or where z.z.z.z makes the request and therefore is the 'originating IP address'
1 of 60 for the hour for z.z.z.z (me)
2 of 60 for the hour for z.z.z.z (you)
3 of 60 for the hour for z.z.z.z (me)
4 of 60 for the hour for z.z.z.z (you)
5 of 60 for the hour for z.z.z.z (me)
6 of 60 for the hour for z.z.z.z (you)
...etc 


Where can this actually go wrong?  On school & business campuses or during a live event.   Anyplace where there is a larger group of people hiding behind the same originating (public) IP address.  

Say you have a post that pops off at a university, or you're some kind of public speaker that goes to a convention center... or you provide in-house training for large corporations.  If a 60+ group of people are connected to the same public wifi at an event hall, and you direct them to go to your blog, you'll hit that limit because all those people are on the same private network and will therefore have the same public originating IP.

In regard to rate-limiting, and not providing a key, Your design here is more fault-tolerant than you give it credit for.  every home in America can simultaneously read your blog at the same moment.  (just try not to do much public speaking ;) )

**Comment by mateogianolio** [comment]
Ahh I re-read your comment and the docs and when reading it from the perspective of a server it makes sense. The "... and not the person making the requests" confused me before. Thank you for the thorough explanation!

The token setup steps should be removed from this README and I'll remove it from casualjavascript org.
